#!/usr/bin/env bash

#Date: 09/03/2022 ## Version del sistema: Linux Mint.Mate.20.2
#Date: 29/03/2022 ## El script fue armado de manera muy basica debido
##Que en mi pc principal no puedo hacer andar linux, he dejado una
#configuracion con las cosas que he utilizado para estudiar, que no es mucho :) 

#ANCI Colors and tput
ENDCOLOR="\e[0m"
BLUELIGHT="\e[1;94m"
YELLOWLIGHT="\e[1;93m"
LIGHTMAGENTA="\e[1;95m"
GREEN="\e[1;32m"
yellowstrong=$(tput setaf 190)

###############################################################################

#ACTUALIZACION DEL SISTEMA Y DIRECTORIOS[1] 

sudo apt update && sudo apt upgrade -y && sleep 3

cd ~/ && mkdir 4kall test && cd 4kall && mkdir PDFs DriverExes Fotos && sleep 3

###############################################################################

#INSTALACION DE LOS PROGRAMAS CON REBOOT OPCIONAL[2]

#Instalacion de 'snapd'
sudo rm /etc/apt/preferences.d/nosnap.pref && sudo apt update && \
sudo apt install snapd -y

#sublime-text install
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key \
add - && sudo apt-get install apt-transport-https && echo \
"deb https://download.sublimetext.com/ apt/stable/" | sudo tee \
/etc/apt/sources.list.d/sublime-text.list && sudo apt-get update && sudo \
apt-get install sublime-text && sleep 2

#navegador brave install
keyring="brave-browser-archive-keyring.gpg"
release="brave-browser-apt-release.s3.brave.com"

sudo apt install apt-transport-https curl && sudo curl -fsSLo \
/usr/share/keyrings/$keyring https://$release/$keyring && echo \
"deb [signed-by=/usr/share/keyrings/$keyring arch=amd64] \
https://$release/ stable main" -y | sudo tee /etc/apt/sources.list.d/\
brave-browser-release.list && sudo apt update && sudo apt install \
brave-browser && sleep 1 && echo -e "${GREEN}FINISH${ENDCOLOR}"

#Google Chrome installation with chrome repository (other option is .deb pack)

sudo apt update && wget -q -O \
- https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - && \
echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
| sudo tee /etc/apt/sources.list.d/google-chrome.list && sudo apt update && \
sudo apt install -y google-chrome-stable && echo -e \
"${GREEN}Google it's ready${ENDCOLOR}"

#Python 3.10 installation

sudo apt install software-properties-common -y
sudo add-apt-repository ppa:deadsnakes/ppa -y && sudo apt update
sudo apt install python3.10 -y
