#!/usr/bin/env bash

#Date: 09/03/2022 el script inicial fue hecho con una configuracion muy basica
#debido a que estaba en una net.
#Vamos a empezar un script que es para que configure mi Linux Mint a como lo 
#uso habitualmente.
#Version del sistema: Linux Mint.Mate.20.2
#Nota de actualizacion al 11/03/2022: Movi el Mint hacia mi pc principal, por
#lo que tuve que cambiar un montonaso...
#de configuraciones, por lo cual el script llamda instalacionLinuxMint2 sera 
#este mismo pero con mas programas y..
#configuraciones a realizar debido a que lo estare usando para jugar tambien.
#Ganas de llorar me da todo el proceso.

#Esto es con la forma de ANSI color codes para este bash script
ENDCOLOR="\e[0m"
BLUELIGHT="\e[1;94m"
YELLOWLIGHT="\e[1;93m"
LIGHTMAGENTA="\e[1;95m"
GREEN="\e[1;32m"

#SON ejemplos estos son utilizados en los ejemplos de abajo
#REDLINE="\e[4;31m"
#echo -e "${BLUE}este texto deberia ser azul${ENDCOLOR}"
#Esto seria con "tput"
yellowstrong=$(tput setaf 190)
#echo -e "${yellowstrong}este texto deberia ser amarillo"

#Esto de abajo es una simple prueba de colores
echo -e "${LIGHTMAGENTA}este texto debe ser magenta liviano${ENDCOLOR}"
echo -e "${BLUELIGHT}azul livianito pa${ENDCOLOR}"
echo -e "${YELLOWLIGHT}amarillo patito pa${ENDCOLOR}"
echo -e "${GREEN}esto es verde pa${ENDCOLOR}"

#Programas que tengo que lograr instalar:
#snapd-Discord-Steam-Navegador Brave-Sublime Text-Mozilla Firefox-Spotifai

#Configuraciones del sistema en general
#sensibildad del mouse, cambio de fondo de pantalla, iconos anclados en la 
#en la barra de tareas, sonidos predeterminados, preferencias de apariencia
#esto teorimcamente es todo lo que debo hacer, poquito por ahora creo.



#Empezamos con el script. Primero una actualizacion de importancia
ACTUALIZADO="El sistema esta actualizado en estos momentos"
sudo apt update && sudo apt upgrade -y && \ 
| echo -e "${GREEN}$ACTUALIZADO${ENDCOLOR}"

#Instalacion de 'snapd'
sudo rm /etc/apt/preferences.d/nosnap.pref && sudo apt update && \ 
| sudo apt install snapd -y && snap install hello-world && hello-world

sleep 2

#Creacion de mis directorios hasta el momento
cd && pwd && mkdir 4kall test && cd 4kall && mkdir PDFs DriverExes Fotos && cd

#Instalaciones de programas con SNAPD
SNAPPS="${GREEN}En proceso de instalar: \nDiscord \nSpotify \nVLC${ENDCOLOR}"

echo -e "${GREEN}$SNAPPS${ENDCOLOR}"; sleep 1

cd test/ && sudo snap install discord && systemctl status discord > discordstat
echo < discordstat && sleep 1 && sudo snap install spotify && \ 
| sudo snap install vlc && echo -e "${YELLOWLIGHT}SNAP ha instalado todo
${ENDCOLOR}"
